# __MODELO DE PREDICCIÓN DEL ABANDONO DE EMPLEADOS DE UNA EMPRESA__
- Curso de Aprendizaje Automático 2024/25
- Grado en Ingeniería Informática - UC3M

__Autores__
- Alejandro López Sancho
- Javier Rosales Lozano

## 1. Importación de los datos y del modelo

Este notebook contiene todo el proceso de predicción del dataset de competición una vez creado el modelo final e importado del anterior Jupyter Notebook.

Primeramente, se importa el [dataset de competición](attrition_competition_02.csv.gz) mencionado en el primer Notebook para visualizar su contenido y modificarlo.

In [10]:
# Importamos librerías
import joblib
import pandas as pd

# Cargamos el modelo y los datos
modelo_final = joblib.load("model.pkl")
nuevos_datos = pd.read_csv("data/attrition_competition_02.csv.gz", compression="gzip", sep=",")

# Extraemos las variables que no sirven de nada
nuevos_datos.drop(columns="EmployeeID")

,hrs,absences,JobInvolvement,PerformanceRating,EnvironmentSatisfaction,JobSatisfaction,WorkLifeBalance,Age,BusinessTravel,Department,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,7.548743,5,3,3,4.0,4.0,3.0,34,Travel_Rarely,Sales,...,5.0,Y,12,8,1,6.0,2,2,2,2
1,7.132307,12,3,3,1.0,2.0,1.0,28,Travel_Rarely,Sales,...,0.0,Y,11,8,0,6.0,4,5,0,4
2,6.734056,13,4,3,4.0,2.0,3.0,35,Travel_Rarely,Research & Development,...,3.0,Y,12,8,1,16.0,3,13,4,8
3,6.574325,12,3,3,1.0,3.0,3.0,56,Travel_Frequently,Research & Development,...,2.0,Y,11,8,0,18.0,4,5,0,3
4,6.607062,15,2,3,2.0,2.0,2.0,35,Travel_Rarely,Sales,...,7.0,Y,16,8,0,10.0,5,7,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,5.749068,23,4,3,3.0,4.0,3.0,29,Travel_Rarely,Research & Development,...,4.0,Y,14,8,0,11.0,3,7,1,7
1466,10.723780,4,3,3,4.0,3.0,1.0,38,Travel_Rarely,Sales,...,6.0,Y,12,8,2,6.0,5,1,0,1
1467,7.054613,20,1,3,4.0,4.0,3.0,41,Travel_Rarely,Sales,...,3.0,Y,17,8,1,12.0,1,5,1,0
1468,6.093781,18,3,3,1.0,3.0,4.0,37,Travel_Rarely,Research & Development,...,4.0,Y,17,8,3,16.0,3,5,0,2
1469,7.589734,4,3,3,3.0,2.0,3.0,35,Travel_Rarely,Research & Development,...,9.0,Y,15,8,0,10.0,2,1,0,0

## 2. Predicciones de los datos de competición

A continuación, se procede a la __predicción del conjunto de competición__:

In [11]:
# Realizamos las predicciones
predicciones = modelo_final.predict(nuevos_datos)

# Guardamos las predicciones en un archivo CSV, convirtiendo los valores 0 y 1 a "No" y "Yes"
df_predicciones = pd.DataFrame(predicciones, columns=["Attrition"])
df_predicciones = df_predicciones.replace({0: "No", 1: "Yes"})
df_predicciones.to_csv("data/predictions.csv", index=False)

Finalmente, se comprueban el número de instancias clasificadas para cada clase:

In [12]:
df_predicciones["Attrition"].value_counts()

Attrition
No     1241
Yes     229
Name: count, dtype: int64